- model: rock_1
  at: T27
  dir:
    - -0.653
    - 0
    - 0.757
  yaw: 0
  scale: 1
- model: tree_3
  at: T35
  dir:
    - -0.177
    - 0.295
    - -0.939
  yaw: 0
  scale: 1
- model: tree_1
  at: T20
  dir:
    - 0.152
    - 0.987
    - 0.057
  yaw: 0
  scale: 1
