import * as THREE from "three";
import { writeFileSync } from "node:fs";
import { createPlayerState, stepPlayer, TICK_DT, type MoveInput } from "../systems/sim.js";
import { createPath } from "../world/path.js";
import type { Planet } from "../world/planet.js";

// Writes the golden file: a fixed list of inputs and the exact path the client's sim walks when it eats
// them. The Go test feeds the same inputs to its own copy of the sim and checks it lands on the same
// points. Change a speed, a turn rate or the road's shape in one language and forget the other, and that
// test fails immediately instead of turning up months later as players twitching for no visible reason.
//
// Run it with `npm run gen:trajectory` from client/. The output is committed, so a fresh clone can run
// the Go test without needing node at all.

// A stand-in planet: the same two bits of arithmetic as world/planet.ts, without building an 80-million
// triangle sphere we would only throw away. The real path IS used, because its meandering shape is
// exactly the sort of thing that drifts between two hand-written copies.
const RADIUS = 36;
const center = new THREE.Vector3(0, 0, 0);
const planet = {
  center,
  radius: RADIUS,
  upAt: (pos: THREE.Vector3, target: THREE.Vector3) => target.copy(pos).sub(center).normalize(),
  placeOnSurface: (pos: THREE.Vector3) => pos.sub(center).setLength(RADIUS).add(center),
} as unknown as Planet;

const path = createPath(new THREE.Scene(), planet);

// The input list. It has to exercise the things that could differ: a long run in one direction, a hard
// reverse, walking, standing still, and enough wandering to cross on and off the dirt road so both
// speeds get used.
function inputAt(i: number): THREE.Vector3 {
  if (i < 60) return new THREE.Vector3(0, 0, 1); // run straight, crosses the road
  if (i < 90) return new THREE.Vector3(0, 0, -1); // dead reverse, the turn's worst case
  if (i < 140) return new THREE.Vector3(0.5, 0, 0.2); // walk, off at an angle
  if (i < 160) return new THREE.Vector3(0, 0, 0); // stand still
  // Then a long curving run, so the facing keeps chasing a moving target.
  const a = (i - 160) * 0.05;
  return new THREE.Vector3(Math.cos(a), 0, Math.sin(a));
}

const TICKS = 400;
const state = createPlayerState(new THREE.Vector3(0, RADIUS, 0));
const steps = [];
for (let i = 0; i < TICKS; i++) {
  const input: MoveInput = { seq: i, dir: inputAt(i) };
  stepPlayer(state, input, planet, path, TICK_DT);
  steps.push({
    dir: [input.dir.x, input.dir.y, input.dir.z],
    position: [state.position.x, state.position.y, state.position.z],
    forward: [state.forward.x, state.forward.y, state.forward.z],
    anim: state.anim,
  });
}

// Written out by hand rather than with JSON.stringify's indenting, which puts every single number on
// its own line and turns three hundred lines into eight thousand. Here a vector stays on one line and a
// tick is one line, so the file can be read, and a change to the walk shows up in a diff as the ticks
// that actually moved.
// Numbers go through JSON.stringify one at a time, which prints the shortest text that reads back as
// exactly the same float64. Rounding for looks would quietly loosen the very thing this file is for.
const num = (n: number) => JSON.stringify(n);
const arr = (v: number[]) => `[${v.map(num).join(", ")}]`;

// The constants go in too. If Go and TypeScript disagree about the tick length or the planet's size,
// the test says so in one line instead of leaving you to work it out from a drifting path.
const lines = [
  "{",
  `  "note": "Generated by client/src/tools/genTrajectory.ts. Do not edit by hand.",`,
  `  "tickDt": ${num(TICK_DT)},`,
  `  "radius": ${num(RADIUS)},`,
  `  "spawn": ${arr([0, RADIUS, 0])},`,
  `  "facing": ${arr([0, 0, 1])},`,
  `  "steps": [`,
  ...steps.map((s, i) => {
    const end = i === steps.length - 1 ? "" : ",";
    return `    { "dir": ${arr(s.dir)}, "position": ${arr(s.position)}, "forward": ${arr(s.forward)}, "anim": ${JSON.stringify(s.anim)} }${end}`;
  }),
  "  ]",
  "}",
  "",
];

const out = "../server/sim/testdata/trajectory.json";
writeFileSync(out, lines.join("\n"));
console.log(`wrote ${steps.length} ticks to ${out}`);
